services:
  web:
    image: ireport_apache_image
    container_name: ireport
    ports:
      - "80:80"
    volumes:
      - C:\Users\PREDATOR\Documents\File Kuliah\Project\Semester 3\iReportEXPO\webfolder:/var/www/html
    networks:
      - appireport
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ireportRoot  # Set the root password here
      MYSQL_DATABASE: ireport  # The name of your database
      MYSQL_USER: ireportUser  # MySQL user
      MYSQL_PASSWORD: ireportPass  # Password for the user
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appireport

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  # Point to the MySQL container
      PMA_USER: ireportUser  # Use the root user
      PMA_PASSWORD: ireportPass  # Use the root password set in db
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    networks:
      - appireport
    depends_on:
      - db

networks:
  appireport:
    external: true

volumes:
  db_data:
    driver: local
